Repository jitsecurity/jit-customer-scripts, pull requests merged in 2023-08, with the labels that each got.

#5 typo
  src/scripts/create_teams.py
  src/utils/github_topics_to_json_file.py
Labels: 1 min review

#7 modify readme to instruct the user to clone a specific release
  README.md
Labels: 1 min review, safe-change

#8 make the Makefile more robust across platforms
  Makefile
Labels: 1 min review

#9 update checkout example code
  README.md
Labels: 1 min review, safe-change

#11 Sc 20043 self hosted runners customer scripts
  Makefile
  README.md
  src/scripts/self-hosted-runners/install-github-runner-agent.sh
  src/scripts/self-hosted-runners/setup-self-hosted-runner-centos.sh
Labels: 10 min review

#12 Update install-github-runner-agent.sh
  src/scripts/self-hosted-runners/install-github-runner-agent.sh
Labels: 1 min review

#13 Sc 20043 self hosted runners customer scripts part2
  Makefile
  README.md
  src/scripts/self-hosted-runners/install-github-runner-agent.sh
  src/scripts/self-hosted-runners/self-hosted-runner.md
  src/scripts/self-hosted-runners/setup-rootless-docker-centos.sh
  src/scripts/self-hosted-runners/setup-rootless-docker-ubuntu.sh
  src/scripts/sync_teams/__init__.py
  src/scripts/sync_teams/sync-teams.md
  src/scripts/sync_teams/sync_teams.py
  tests/scripts/test_sync_teams.py
  tests/shared/test_unit.py
Labels: 5 min review

#14 don't delete teams that were not manually created
  src/scripts/sync_teams/sync_teams.py
  src/shared/clients/jit.py
Labels: 1 min review
